package com.mimo.analysis.agent;

import com.mimo.analysis.core.filter.ClassFilter;
import com.mimo.analysis.core.filter.DefaultClassFilter;
import com.mimo.analysis.core.util.ClassNameUtils;

import java.io.*;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Agent 数据收集器，负责收集 Java Agent 在运行时检测到的类加载信息。
 *
 * 该类是线程安全的，使用 {@link ConcurrentHashMap} 的 KeySet 作为并发集合，
 * 因为类加载可能发生在多个线程中。
 *
 * 工作流程：
 * 1. {@link #initialize(String, ClassFilter)} 初始化输出文件路径和过滤器
 * 2. {@link #recordClass(String)} 在每次类加载时被调用，记录被加载的类
 * 3. {@link #saveResults()} 在 JVM 关闭时（shutdown hook）被调用，将结果写入文件
 *
 * 输出文件格式为纯文本，每行一个类的全限定名，按字母序排列。
 */
public class AgentDataCollector {

    /** 已收集的类名集合，使用 ConcurrentHashMap.KeySet 保证线程安全 */
    private static final Set<String> collectedClasses = ConcurrentHashMap.newKeySet();

    /** 输出文件路径，在初始化时设置 */
    private static volatile String outputFile;

    /** 类过滤器，在初始化时设置，用于排除不需要记录的类 */
    private static volatile ClassFilter filter;

    /**
     * 初始化数据收集器。
     * 在 Agent 启动时调用，设置输出文件路径和过滤规则。
     *
     * @param output     输出文件路径
     * @param classFilter 类过滤器
     */
    public static void initialize(String output, ClassFilter classFilter) {
        outputFile = output;
        filter = classFilter;
    }

    /**
     * 记录一个被加载的类。
     * 在每次类加载时由 {@link ClassUsageTransformer} 调用。
     *
     * 处理流程：
     * 1. 忽略 null 或空类名
     * 2. 将 JVM 内部格式（'/' 分隔）转换为标准格式（'.' 分隔）
     * 3. 通过过滤器排除不需要记录的类
     * 4. 将类名添加到已收集集合中（自动去重）
     *
     * @param className 被加载类的 JVM 内部名（使用 '/' 分隔）
     */
    public static void recordClass(String className) {
        if (className == null || className.isEmpty()) return;

        // 转换为标准点分隔格式
        String dotName = ClassNameUtils.toDotNotation(className);

        // 过滤被排除的类
        if (filter != null && filter.shouldExclude(dotName)) {
            return;
        }

        // 添加到已收集集合（ConcurrentHashMap.KeySet 自动去重）
        collectedClasses.add(dotName);
    }

    /**
     * 将收集到的类列表保存到输出文件。
     * 在 JVM 关闭时通过 shutdown hook 自动调用。
     *
     * 输出格式：
     * - 前 4 行为注释头（标题、来源、类总数、分隔线）
     * - 后续每行一个类的全限定名，按字母序排列
     */
    public static void saveResults() {
        if (outputFile == null) return;

        // 排序后输出
        List<String> sorted = new ArrayList<>(collectedClasses);
        Collections.sort(sorted);

        try (PrintWriter writer = new PrintWriter(new FileWriter(outputFile))) {
            // 输出文件头
            writer.println("# Class Usage Analysis - Agent Output");
            writer.println("# Generated by Java Agent");
            writer.println("# Total classes loaded: " + sorted.size());
            writer.println("#");
            // 输出所有类名
            for (String className : sorted) {
                writer.println(className);
            }
            System.out.println("[ClassUsageAgent] Results saved to " + outputFile
                    + " (" + sorted.size() + " classes)");
        } catch (IOException e) {
            System.err.println("[ClassUsageAgent] Failed to save results: " + e.getMessage());
        }
    }

    /**
     * 获取已收集的类名集合的不可修改视图。
     *
     * @return 已收集的类名集合
     */
    public static Set<String> getCollectedClasses() {
        return Collections.unmodifiableSet(collectedClasses);
    }

    /**
     * 获取已收集的类总数。
     *
     * @return 已收集的类数量
     */
    public static int getClassCount() {
        return collectedClasses.size();
    }
}
