package com.mimo.analysis.agent;

import com.mimo.analysis.core.filter.ClassFilter;
import com.mimo.analysis.core.filter.DefaultClassFilter;
import com.mimo.analysis.core.util.ClassNameUtils;

import java.io.*;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;

public class AgentDataCollector {

    private static final Set<String> collectedClasses = ConcurrentHashMap.newKeySet();
    private static volatile String outputFile;
    private static volatile ClassFilter filter;

    public static void initialize(String output, ClassFilter classFilter) {
        outputFile = output;
        filter = classFilter;
    }

    public static void recordClass(String className) {
        if (className == null || className.isEmpty()) return;

        String dotName = ClassNameUtils.toDotNotation(className);

        if (filter != null && filter.shouldExclude(dotName)) {
            return;
        }

        collectedClasses.add(dotName);
    }

    public static void saveResults() {
        if (outputFile == null) return;

        List<String> sorted = new ArrayList<>(collectedClasses);
        Collections.sort(sorted);

        try (PrintWriter writer = new PrintWriter(new FileWriter(outputFile))) {
            writer.println("# Class Usage Analysis - Agent Output");
            writer.println("# Generated by Java Agent");
            writer.println("# Total classes loaded: " + sorted.size());
            writer.println("#");
            for (String className : sorted) {
                writer.println(className);
            }
            System.out.println("[ClassUsageAgent] Results saved to " + outputFile
                    + " (" + sorted.size() + " classes)");
        } catch (IOException e) {
            System.err.println("[ClassUsageAgent] Failed to save results: " + e.getMessage());
        }
    }

    public static Set<String> getCollectedClasses() {
        return Collections.unmodifiableSet(collectedClasses);
    }

    public static int getClassCount() {
        return collectedClasses.size();
    }
}
